language: objective-c
osx_image: xcode8.3
cache: cocoapods
branches:
  only:
  - master
before_install:
- pod repo update > /dev/null
script: "xcodebuild -workspace MIST.xcworkspace -scheme MIST -sdk iphonesimulator"
